/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkspaceLayoutImport } from './routes/_workspaceLayout'
import { Route as SignUpIndexImport } from './routes/sign-up/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as WorkspaceLayoutWorkspacesWorkspaceIdImport } from './routes/_workspaceLayout/workspaces/$workspaceId'
import { Route as WorkspaceLayoutBoardsBoardIdImport } from './routes/_workspaceLayout/boards/$boardId'

// Create/Update Routes

const WorkspaceLayoutRoute = WorkspaceLayoutImport.update({
  id: '/_workspaceLayout',
  getParentRoute: () => rootRoute,
} as any)

const SignUpIndexRoute = SignUpIndexImport.update({
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceLayoutWorkspacesWorkspaceIdRoute =
  WorkspaceLayoutWorkspacesWorkspaceIdImport.update({
    path: '/workspaces/$workspaceId',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)

const WorkspaceLayoutBoardsBoardIdRoute =
  WorkspaceLayoutBoardsBoardIdImport.update({
    path: '/boards/$boardId',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspaceLayout': {
      preLoaderRoute: typeof WorkspaceLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      preLoaderRoute: typeof SignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/_workspaceLayout/boards/$boardId': {
      preLoaderRoute: typeof WorkspaceLayoutBoardsBoardIdImport
      parentRoute: typeof WorkspaceLayoutImport
    }
    '/_workspaceLayout/workspaces/$workspaceId': {
      preLoaderRoute: typeof WorkspaceLayoutWorkspacesWorkspaceIdImport
      parentRoute: typeof WorkspaceLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  WorkspaceLayoutRoute.addChildren([
    WorkspaceLayoutBoardsBoardIdRoute,
    WorkspaceLayoutWorkspacesWorkspaceIdRoute,
  ]),
  LoginIndexRoute,
  SignUpIndexRoute,
])

/* prettier-ignore-end */
